### ISSUE TITLE
Error in Step 4A of Analysis Pipeline due to Invalid or Deleted Figure

### ISSUE THREAD

**Issue by davidioluigbo** [SAND-Lab/AnalysisPipeline#18]
When I have tried running the most recent version of the pipeline, I have successfully been able to complete steps 1-3. However, on step 4A, I have received the following error with several datasets. 

**Error using matlab.ui.Figure/set
Invalid or deleted object.

Error in biAdvancedSettings (line 209)
    set(Params.oneFigure, 'Position', p);

Error in MEApipeline (line 381)
        biAdvancedSettings  % Temp here to try out new NMF code**

**Comment by Timothysit** [comment]
Hi David, this is likely caused by the figure object being deleted at this point of the pipeline, or the figure object being loaded from a previous `Params` file being closed and therefore deleted. I have now added some checks in the code to check if the figure handle is deleted, and if so make a new one, see if it works and let me know!

Reference to this commit: https://github.com/SAND-Lab/AnalysisPipeline/commit/85f2f481bfc14cf49dd757540e1da27de553ec88

**Comment by davidioluigbo** [comment]
I no longer encountered this error when I re-ran step 4A of pipeline on some sample Organoid data (two .mat files).
