### ISSUE TITLE
(Step 1B) Blank SpikeFrequencies .png and .svg Files 

### ISSUE THREAD

**Issue by davidioluigbo** [SAND-Lab/AnalysisPipeline#22]
After using the  the updated version of the pipeline released last week for a while now, I just noticed that my SpikeFrequencies .png and .svg files are now blank for step 1B. Currently, I am not sure how the code in the pipeline changed to prompt this error. I am also not entirely sure if this impacts downstream steps of the pipeline (thresholding, network activity, etc.). 

![image](https://user-images.githubusercontent.com/95871175/187922620-8b989a08-6b06-4d7e-9ebc-0c156b8a233b.png)

**Comment by Timothysit** [comment]
Hi David, this issue seems to be fixed after I changed the figure positioning, weird but seem to solve it. This is in commit 01bac6e9e6b62c449e820e213acb43094027fbe3. Please run through the pipeline again to double check just in case this is caused by something upstream that I didn't do in my test, and I will re-open the issue if this is not fixed.
